# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPv4Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
                ('allocated_for_request', models.CharField(max_length=36, null=True)),
            ],
        ),
    ]
