# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPv4Whois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, b'Awaiting Registry'), (1, b'Looking up Registry'), (2, b'failed to find Registry'), (3, b'Found Registry'), (4, b'Looking up WHOIS'), (5, b'Failed to lookup WHOIS'), (6, b'Got WHOIS')], default=0)),
                ('address', models.GenericIPAddressField()),
                ('whois', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
